# Generated by Django 2.0.13 on 2019-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=45, unique=True)),
                ('user_password', models.CharField(max_length=45)),
                ('user_nick_name', models.CharField(max_length=45, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'ordering': ['-created_date'],
            },
        ),
    ]
