# Generated by Django 2.0.13 on 2019-06-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190604_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_date',
        ),
    ]
