# Generated by Django 2.0.13 on 2019-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_certificate_cert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
