# Generated by Django 2.0.13 on 2019-06-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
